version: '3.8'
services:
  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=UserServiceDb;Trusted_Connection=True;TrustServerCertificate=True;
    ports:
      - "5001:8080"

  reservationservice:
    build:
      context: .
      dockerfile: ReservationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=ReservationServiceDb;Trusted_Connection=True;TrustServerCertificate=True;
    ports:
      - "5002:8080"

  predictionservice:
    build:
      context: .
      dockerfile: PredictionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=PredictionServiceDb;Trusted_Connection=True;TrustServerCertificate=True;
    ports:
      - "5003:8080" 